# Generated by Django 4.1.3 on 2022-12-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='status_text',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='text_message',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
