# Generated by Django 4.1.3 on 2023-01-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_endtdatetime_alter_task_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='endtdatetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='filter',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='message',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='startdatetime',
            field=models.DateTimeField(),
        ),
    ]
