# Generated by Django 4.1.3 on 2023-01-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_endtdatetime_alter_task_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('CR', 'Create'), ('SD', 'Sending'), ('ER', 'Error'), ('OK', 'OK')], default='CR', max_length=2),
        ),
    ]
