# Generated by Django 4.1.3 on 2023-01-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NN', 'None'), ('ST', 'Start'), ('WK', 'Work'), ('ER', 'Error'), ('WR', 'Warning'), ('ED', 'End')], default='NN', max_length=2),
        ),
    ]
