# Generated by Django 4.1.3 on 2023-02-03 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('SD', 'Sending'), ('ER', 'Error'), ('OK', 'OK')], default='CR', max_length=2),
        ),
        migrations.AlterField(
            model_name='message',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='client_messages', to='task.task'),
        ),
    ]
