# Generated by Django 4.1.3 on 2022-12-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=100)),
                ('code', models.CharField(default='', max_length=100)),
                ('tag', models.CharField(default='', max_length=2000)),
                ('status', models.CharField(default='', max_length=20)),
                ('status_text', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
