# Generated by Django 4.1.3 on 2023-01-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_code_alter_client_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='tag',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='client',
            name='utc',
            field=models.IntegerField(default=0),
        ),
    ]
